### ISSUE TITLE
Support tailing logs

### ISSUE THREAD

**Issue by lukemarsden** [jonathanj/eliottree#11]
It would be really nice if this could incrementally render tailed logs.

**Comment by mithrandi** [comment]
Incremental rendering is kinda tricky because you have to go back to put messages into older task trees; you'd either need a different rendering format, or the ability to redraw the entire display.

**Comment by jonathanj** [comment]
I had thought about this but ran into a (quite a large) snag: Since the output is just a bunch of lines written to a terminal (as opposed to a web UI or a curses UI), how do you know when to output something?

In other words, at what point do you know that a top-level task has no more actions or messages that have yet to appear? One could emit the complete tree for a task when a new sub-task for that task UUID appears but I'm not sure how you would avoid the torrent of output from several sub-tasks appearing in succession.

**Comment by jonathanj** [comment]
@lukemarsden If you have an idea for an alternate mode of operation that is suitable for some kind of incremental mode, I'd really appreciate the insight!

**Comment by jerith** [comment]
You could treat a task as "complete" when every action start (including the top-level action in the task) has a matching action end (success or failure) or if some (configurable) amount of time has passed since the last message in the task.

That said, I'm not sure how useful this would be in practice. If I'm tailing logs, I'm generally more interested in what's happening now than what tasks have "completed" recently.

**Comment by exarkun** [comment]
Here's an idea for a somewhat (but not entirely) different output format that I think would work well for this feature.  I don't think it will work very well in a terminal but I think it could work using some other interface.  Imagine something that supports a bunch of tabs, for example.

Render trees as they are constructed.  As they are updated, update the display.

Make all trees available for viewing (but only display as many as can reasonably fit onto the display at once).

Offer options to highlight or focus trees based on certain conditions.  The most obvious condition being "the tree just changed".  Other conditions could be "the tree just gained an error".

Highlight the portions of a tree that are new since the last render.

Allow trees to be marked as interesting to hold them in focus longer than they might otherwise be held.

Offer an expressive configuration tool for controlling most aspects of this (maybe an expression language that drives the display - eg, selects trees for display / focus, selects trees to age out, defines conditions for other actions in the ui, etc) and  way to persist the configuration so developers can build a workflow that works for their particular application (avoiding the need to have a workflow that works for all Eliot-based applications).

**Comment by jonathanj** [comment]
Thanks for making that comment, it's a great outline for a more capable tool than eliottree. On my list of projects I want to one day (in the near future) get around to, I'd like to write something much like what you've explained here as some kind of graphical application. Something I hadn't really thought about was the idea of "workflows", these are a fantastic idea.

**Comment by jonathanj** [comment]
To summarise some conversations that have been had about this topic via other mediums:

As far as eliottree currently stands, the output medium is append-only (writing lines to stdout) which only really lends itself to emitting an entire tree again if any part of it changed. It's also possible to implement something with a UI library like `ncurses` but ultimately both of these ideas are a nontrivial amount of work and—certainly for what my goal is—the effort is better spent building a tool that takes a different approach and leaving eliottree on its current path.
